#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          anytermd
# Required-Start:    $syslog $local_fs $remote_fs
# Required-Stop:     $syslog $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts/stops anytermd
# Description:       starts and stops Anyterm,
#					a very tiny web based terminal
# Version: zf120719.2038
### END INIT INFO

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
DAEMON=/usr/bin/anytermd
PORT=8023
SERVERPORT=22
PIDFILE=/var/run/anytermd.pid
NAME=anytermd
DESC="web based terminal"
anytermd_UID=zulu
anytermd_GID=zulu

if [ $(id -u) != 0 ]; then
  echo "You should run this program as root"
  exit 1
fi

[ -x "$DAEMON" ] || exit 0

[ -f "/etc/default/anytermd" ] && . /etc/default/anytermd

. /lib/lsb/init-functions

case "$1" in
	start)
		log_begin_msg "Starting $DESC:" "$NAME"
		if [ -f $PIDFILE ]; then
			log_action_cont_msg " already running"
			log_end_msg 1
		else
#			start-stop-daemon --start --group=$anytermd_GID --pidfile $PIDFILE --exec $DAEMON -- --daemon --port=$PORT --serverport=$SERVERPORT \
#				--uid=$anytermd_UID >/dev/null
			start-stop-daemon --start --group=$anytermd_GID --pidfile $PIDFILE --exec $DAEMON -- \
				-p $PORT -u $anytermd_UID --local-only -c '/usr/share/anyterm/run_ssh.sh' >/dev/null
			log_end_msg $?
		fi
	;;
	stop)
		log_begin_msg "Stopping $DESC:" "$NAME"
		start-stop-daemon --stop --pidfile $PIDFILE
		rm -f $PIDFILE
		log_end_msg $?
	;;
	restart|force-reload)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
		exit 3
	;;
esac
