#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          inadyn
# Required-Start:    $syslog $local_fs $remote_fs
# Required-Stop:     $syslog $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts/stops inadyn
# Description:       starts and stops inadyn
# Version: zf120726.1726
### END INIT INFO

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
DAEMON=/usr/sbin/inadyn
NAME=inadyn
DESC="Dynamic IP update"

startDyn() {
    $DAEMON --input_file /home/zulu/Perso/inadyn.conf
}

test -x $DAEMON || exit 0

case "$1" in
   start)
       echo -n "Starting $DESC: $NAME"
       startDyn
       echo "."
       ;;
   stop)
       echo -n "Stopping $DESC: $NAME"
       killall $NAME
       echo "."
       ;;
   restart)
       $0 stop
       $0 start
       echo "."
       ;;
   *)
       echo "Usage: /etc/init.d/$NAME start|stop|restart" >&2
       exit 1
       ;;
esac

exit 0

